import { test, expect } from '@playwright/test';
import { ApplicationFormPage } from '../../pages/ApplicationFormPage';

/**
 * SP-1944 - Network Challenge Application Link - User Side
  * EN: https://gca.stg.alweb4tech.com/en/Network-Challenge
   * AR: https://gca.stg.alweb4tech.com/Network-Challenge
    * Public pages - no login required
     */
     test.describe('SP-1944 | Network Challenge User Side @smoke @regression', () => {
       let formPage: ApplicationFormPage;

         test.beforeEach(async ({ page }) => {
             formPage = new ApplicationFormPage(page);
               });

                 test('@SP-1944 @smoke @lang-en Network Challenge EN page loads', async ({ page }) => {
                     await formPage.gotoNetworkChallengeEn();
                         await expect(page).toHaveURL(/\/en\/Network-Challenge/i);
                             expect(await formPage.isPageLoaded()).toBeTruthy();
                               });

                                 test('@SP-1944 @smoke @lang-en Network Challenge EN page is LTR', async ({ page }) => {
                                     await formPage.gotoNetworkChallengeEn();
                                         expect(await formPage.getHtmlDir()).toBe('ltr');
                                           });

                                             test('@SP-1944 @smoke @lang-en Network Challenge EN heading is in English', async ({ page }) => {
                                                 await formPage.gotoNetworkChallengeEn();
                                                     const heading = await formPage.getHeadingText();
                                                         expect(heading).toMatch(/[a-zA-Z]/);
                                                           });

                                                             test('@SP-1944 @smoke @lang-ar Network Challenge AR page loads', async ({ page }) => {
                                                                 await formPage.gotoNetworkChallengeAr();
                                                                     await expect(page).not.toHaveURL(/\/en\//);
                                                                         expect(await formPage.isPageLoaded()).toBeTruthy();
                                                                           });

                                                                             test('@SP-1944 @smoke @lang-ar Network Challenge AR page is RTL', async ({ page }) => {
                                                                                 await formPage.gotoNetworkChallengeAr();
                                                                                     expect(await formPage.getHtmlDir()).toBe('rtl');
                                                                                       });

                                                                                         test('@SP-1944 @smoke @lang-ar Network Challenge AR heading contains Arabic', async ({ page }) => {
                                                                                             await formPage.gotoNetworkChallengeAr();
                                                                                                 const heading = await formPage.getHeadingText();
                                                                                                     expect(heading).toMatch(/[\u0600-\u06FF]/);
                                                                                                       });
                                                                                                       
                                                                                                         test('@SP-1944 @seo Network Challenge EN page is NOT crawlable', async ({ page }) => {
                                                                                                             await formPage.gotoNetworkChallengeEn();
                                                                                                                 const robotsContent = await formPage.getMetaRobotsContent();
                                                                                                                     const robotsTxt = await formPage.checkRobotsTxt('https://gca.stg.alweb4tech.com');
                                                                                                                         expect(robotsContent.includes('noindex') || robotsTxt.includes('/Network-Challenge')).toBeTruthy();
                                                                                                                           });
                                                                                                                           
                                                                                                                             test('@SP-1944 @seo Network Challenge AR page is NOT crawlable', async ({ page }) => {
                                                                                                                                 await formPage.gotoNetworkChallengeAr();
                                                                                                                                     const robotsContent = await formPage.getMetaRobotsContent();
                                                                                                                                         const robotsTxt = await formPage.checkRobotsTxt('https://gca.stg.alweb4tech.com');
                                                                                                                                             expect(robotsContent.includes('noindex') || robotsTxt.includes('/Network-Challenge')).toBeTruthy();
                                                                                                                                               });
                                                                                                                                               
                                                                                                                                                 test('@SP-1944 @smoke Network Challenge EN is publicly accessible without login', async ({ browser }) => {
                                                                                                                                                     const context = await browser.newContext();
                                                                                                                                                         const page = await context.newPage();
                                                                                                                                                             const fp = new ApplicationFormPage(page);
                                                                                                                                                                 await fp.gotoNetworkChallengeEn();
                                                                                                                                                                     expect(await fp.isPageLoaded()).toBeTruthy();
                                                                                                                                                                         await context.close();
                                                                                                                                                                           });
                                                                                                                                                                           
                                                                                                                                                                             test('@SP-1944 @smoke Network Challenge AR is publicly accessible without login', async ({ browser }) => {
                                                                                                                                                                                 const context = await browser.newContext();
                                                                                                                                                                                     const page = await context.newPage();
                                                                                                                                                                                         const fp = new ApplicationFormPage(page);
                                                                                                                                                                                             await fp.gotoNetworkChallengeAr();
                                                                                                                                                                                                 expect(await fp.isPageLoaded()).toBeTruthy();
                                                                                                                                                                                                     await context.close();
                                                                                                                                                                                                       });
                                                                                                                                                                                                       
                                                                                                                                                                                                         test('@SP-1944 @regression @lang-en User submits Network Challenge application in EN', async ({ page }) => {
                                                                                                                                                                                                             await formPage.gotoNetworkChallengeEn();
                                                                                                                                                                                                                 if (await formPage.isFormVisible()) {
                                                                                                                                                                                                                       await formPage.fillApplicationForm({
                                                                                                                                                                                                                               name: 'Test Applicant EN',
                                                                                                                                                                                                                                       email: 'test.en@example.com',
                                                                                                                                                                                                                                               phone: '+971500000001',
                                                                                                                                                                                                                                                       organization: 'Test Org EN',
                                                                                                                                                                                                                                                             });
                                                                                                                                                                                                                                                                   await formPage.submitForm();
                                                                                                                                                                                                                                                                         expect(await formPage.successMessage.isVisible()).toBeTruthy();
                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                               });
                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                 test('@SP-1944 @regression @lang-ar User submits Network Challenge application in AR', async ({ page }) => {
                                                                                                                                                                                                                                                                                     await formPage.gotoNetworkChallengeAr();
                                                                                                                                                                                                                                                                                         if (await formPage.isFormVisible()) {
                                                                                                                                                                                                                                                                                               await formPage.fillApplicationForm({
                                                                                                                                                                                                                                                                                                       name: 'مقدم الطلب',
                                                                                                                                                                                                                                                                                                               email: 'test.ar@example.com',
                                                                                                                                                                                                                                                                                                                       phone: '+971500000002',
                                                                                                                                                                                                                                                                                                                               organization: 'منظمة اختبار',
                                                                                                                                                                                                                                                                                                                                     });
                                                                                                                                                                                                                                                                                                                                           await formPage.submitForm();
                                                                                                                                                                                                                                                                                                                                                 expect(await formPage.successMessage.isVisible()).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                       });
                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                         test('@SP-1944 @negative @lang-en Empty form shows validation errors EN', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                             await formPage.gotoNetworkChallengeEn();
                                                                                                                                                                                                                                                                                                                                                                 if (await formPage.isFormVisible()) {
                                                                                                                                                                                                                                                                                                                                                                       await formPage.submitForm();
                                                                                                                                                                                                                                                                                                                                                                             const errors = await formPage.getValidationErrors();
                                                                                                                                                                                                                                                                                                                                                                                   expect(errors.length).toBeGreaterThan(0);
                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                           test('@SP-1944 @negative @lang-ar Empty form shows validation errors AR', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                               await formPage.gotoNetworkChallengeAr();
                                                                                                                                                                                                                                                                                                                                                                                                   if (await formPage.isFormVisible()) {
                                                                                                                                                                                                                                                                                                                                                                                                         await formPage.submitForm();
                                                                                                                                                                                                                                                                                                                                                                                                               const errors = await formPage.getValidationErrors();
                                                                                                                                                                                                                                                                                                                                                                                                                     expect(errors.length).toBeGreaterThan(0);
                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                           });
                                                                                                                                                                                                                                                                                                                                                                                                                           });
