import { test, expect } from '@playwright/test';
import { ApplicationFormPage } from '../../pages/ApplicationFormPage';

/**
 * SP-1939 - Universities Challenge Application Link - User Side
  * EN: https://gca.stg.alweb4tech.com/en/universities-challenge
   * AR: https://gca.stg.alweb4tech.com/universities-challenge
    */
    test.describe('SP-1939 | Universities Challenge User Side @smoke @regression', () => {
      let formPage: ApplicationFormPage;

        test.beforeEach(async ({ page }) => {
            formPage = new ApplicationFormPage(page);
              });

                test('@SP-1939 @smoke @lang-en Universities Challenge EN page loads', async ({ page }) => {
                    await formPage.gotoUniversitiesChallengeEn();
                        await expect(page).toHaveURL(/\/en\/universities-challenge/i);
                            expect(await formPage.isPageLoaded()).toBeTruthy();
                              });

                                test('@SP-1939 @smoke @lang-en Universities Challenge EN page is LTR', async ({ page }) => {
                                    await formPage.gotoUniversitiesChallengeEn();
                                        expect(await formPage.getHtmlDir()).toBe('ltr');
                                          });

                                            test('@SP-1939 @smoke @lang-en Universities EN heading is in English', async ({ page }) => {
                                                await formPage.gotoUniversitiesChallengeEn();
                                                    const heading = await formPage.getHeadingText();
                                                        expect(heading).toMatch(/[a-zA-Z]/);
                                                          });

                                                            test('@SP-1939 @smoke @lang-ar Universities Challenge AR page loads', async ({ page }) => {
                                                                await formPage.gotoUniversitiesChallengeAr();
                                                                    await expect(page).not.toHaveURL(/\/en\//);
                                                                        expect(await formPage.isPageLoaded()).toBeTruthy();
                                                                          });

                                                                            test('@SP-1939 @smoke @lang-ar Universities Challenge AR page is RTL', async ({ page }) => {
                                                                                await formPage.gotoUniversitiesChallengeAr();
                                                                                    expect(await formPage.getHtmlDir()).toBe('rtl');
                                                                                      });

                                                                                        test('@SP-1939 @smoke @lang-ar Universities AR heading contains Arabic text', async ({ page }) => {
                                                                                            await formPage.gotoUniversitiesChallengeAr();
                                                                                                const heading = await formPage.getHeadingText();
                                                                                                    expect(heading).toMatch(/[\u0600-\u06FF]/);
                                                                                                      });
                                                                                                      
                                                                                                        test('@SP-1939 @seo Universities EN page is NOT crawlable', async ({ page }) => {
                                                                                                            await formPage.gotoUniversitiesChallengeEn();
                                                                                                                const robotsContent = await formPage.getMetaRobotsContent();
                                                                                                                    const robotsTxt = await formPage.checkRobotsTxt('https://gca.stg.alweb4tech.com');
                                                                                                                        const notCrawlable = robotsContent.includes('noindex') || robotsTxt.includes('/universities-challenge');
                                                                                                                            expect(notCrawlable).toBeTruthy();
                                                                                                                              });
                                                                                                                              
                                                                                                                                test('@SP-1939 @seo Universities AR page is NOT crawlable', async ({ page }) => {
                                                                                                                                    await formPage.gotoUniversitiesChallengeAr();
                                                                                                                                        const robotsContent = await formPage.getMetaRobotsContent();
                                                                                                                                            const robotsTxt = await formPage.checkRobotsTxt('https://gca.stg.alweb4tech.com');
                                                                                                                                                const notCrawlable = robotsContent.includes('noindex') || robotsTxt.includes('/universities-challenge');
                                                                                                                                                    expect(notCrawlable).toBeTruthy();
                                                                                                                                                      });
                                                                                                                                                      
                                                                                                                                                        test('@SP-1939 @smoke Universities EN is publicly accessible without login', async ({ browser }) => {
                                                                                                                                                            const context = await browser.newContext();
                                                                                                                                                                const page = await context.newPage();
                                                                                                                                                                    const fp = new ApplicationFormPage(page);
                                                                                                                                                                        await fp.gotoUniversitiesChallengeEn();
                                                                                                                                                                            expect(await fp.isPageLoaded()).toBeTruthy();
                                                                                                                                                                                await context.close();
                                                                                                                                                                                  });
                                                                                                                                                                                  
                                                                                                                                                                                    test('@SP-1939 @smoke Universities AR is publicly accessible without login', async ({ browser }) => {
                                                                                                                                                                                        const context = await browser.newContext();
                                                                                                                                                                                            const page = await context.newPage();
                                                                                                                                                                                                const fp = new ApplicationFormPage(page);
                                                                                                                                                                                                    await fp.gotoUniversitiesChallengeAr();
                                                                                                                                                                                                        expect(await fp.isPageLoaded()).toBeTruthy();
                                                                                                                                                                                                            await context.close();
                                                                                                                                                                                                              });
                                                                                                                                                                                                              
                                                                                                                                                                                                                test('@SP-1939 @regression @lang-en User submits Universities application in EN', async ({ page }) => {
                                                                                                                                                                                                                    await formPage.gotoUniversitiesChallengeEn();
                                                                                                                                                                                                                        if (await formPage.isFormVisible()) {
                                                                                                                                                                                                                              await formPage.fillApplicationForm({
                                                                                                                                                                                                                                      name: 'University Applicant EN',
                                                                                                                                                                                                                                              email: 'uni.en@example.com',
                                                                                                                                                                                                                                                      phone: '+971500000003',
                                                                                                                                                                                                                                                              organization: 'Test University EN',
                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                          await formPage.submitForm();
                                                                                                                                                                                                                                                                                expect(await formPage.successMessage.isVisible()).toBeTruthy();
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                        test('@SP-1939 @regression @lang-ar User submits Universities application in AR', async ({ page }) => {
                                                                                                                                                                                                                                                                                            await formPage.gotoUniversitiesChallengeAr();
                                                                                                                                                                                                                                                                                                if (await formPage.isFormVisible()) {
                                                                                                                                                                                                                                                                                                      await formPage.fillApplicationForm({
                                                                                                                                                                                                                                                                                                              name: 'مقدم طلب الجامعة',
                                                                                                                                                                                                                                                                                                                      email: 'uni.ar@example.com',
                                                                                                                                                                                                                                                                                                                              phone: '+971500000004',
                                                                                                                                                                                                                                                                                                                                      organization: 'جامعة اختبار',
                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                  await formPage.submitForm();
                                                                                                                                                                                                                                                                                                                                                        expect(await formPage.successMessage.isVisible()).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                test('@SP-1939 @negative @lang-en Empty form submission shows errors in EN', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                    await formPage.gotoUniversitiesChallengeEn();
                                                                                                                                                                                                                                                                                                                                                                        if (await formPage.isFormVisible()) {
                                                                                                                                                                                                                                                                                                                                                                              await formPage.submitForm();
                                                                                                                                                                                                                                                                                                                                                                                    const errors = await formPage.getValidationErrors();
                                                                                                                                                                                                                                                                                                                                                                                          expect(errors.length).toBeGreaterThan(0);
                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                  test('@SP-1939 @negative @lang-ar Empty form submission shows errors in AR', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                      await formPage.gotoUniversitiesChallengeAr();
                                                                                                                                                                                                                                                                                                                                                                                                          if (await formPage.isFormVisible()) {
                                                                                                                                                                                                                                                                                                                                                                                                                await formPage.submitForm();
                                                                                                                                                                                                                                                                                                                                                                                                                      const errors = await formPage.getValidationErrors();
                                                                                                                                                                                                                                                                                                                                                                                                                            expect(errors.length).toBeGreaterThan(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                  });
