import { test, expect } from '@playwright/test';
import { ApplicationFormPage } from '../../pages/ApplicationFormPage';

/**
 * SP-1940 - Start-Up Challenge Application Link - User Side
  * EN: https://gca.stg.alweb4tech.com/en/Start-Up-Challenge
   * AR: https://gca.stg.alweb4tech.com/Start-Up-Challenge
    */
    test.describe('SP-1940 | Start-Up Challenge User Side @smoke @regression', () => {
      let formPage: ApplicationFormPage;

        test.beforeEach(async ({ page }) => {
            formPage = new ApplicationFormPage(page);
              });

                test('@SP-1940 @smoke @lang-en Start-Up Challenge EN page loads', async ({ page }) => {
                    await formPage.gotoStartUpChallengeEn();
                        await expect(page).toHaveURL(/\/en\/Start-Up-Challenge/i);
                            expect(await formPage.isPageLoaded()).toBeTruthy();
                              });

                                test('@SP-1940 @smoke @lang-en Start-Up Challenge EN is LTR', async ({ page }) => {
                                    await formPage.gotoStartUpChallengeEn();
                                        expect(await formPage.getHtmlDir()).toBe('ltr');
                                          });

                                            test('@SP-1940 @smoke @lang-en Start-Up EN heading is in English', async ({ page }) => {
                                                await formPage.gotoStartUpChallengeEn();
                                                    const heading = await formPage.getHeadingText();
                                                        expect(heading).toMatch(/[a-zA-Z]/);
                                                          });

                                                            test('@SP-1940 @smoke @lang-ar Start-Up Challenge AR page loads', async ({ page }) => {
                                                                await formPage.gotoStartUpChallengeAr();
                                                                    await expect(page).not.toHaveURL(/\/en\//);
                                                                        expect(await formPage.isPageLoaded()).toBeTruthy();
                                                                          });

                                                                            test('@SP-1940 @smoke @lang-ar Start-Up Challenge AR is RTL', async ({ page }) => {
                                                                                await formPage.gotoStartUpChallengeAr();
                                                                                    expect(await formPage.getHtmlDir()).toBe('rtl');
                                                                                      });

                                                                                        test('@SP-1940 @smoke @lang-ar Start-Up AR heading contains Arabic', async ({ page }) => {
                                                                                            await formPage.gotoStartUpChallengeAr();
                                                                                                const heading = await formPage.getHeadingText();
                                                                                                    expect(heading).toMatch(/[\u0600-\u06FF]/);
                                                                                                      });
                                                                                                      
                                                                                                        test('@SP-1940 @seo Start-Up EN page is NOT crawlable', async ({ page }) => {
                                                                                                            await formPage.gotoStartUpChallengeEn();
                                                                                                                const robotsContent = await formPage.getMetaRobotsContent();
                                                                                                                    const robotsTxt = await formPage.checkRobotsTxt('https://gca.stg.alweb4tech.com');
                                                                                                                        const notCrawlable = robotsContent.includes('noindex') || robotsTxt.includes('/Start-Up-Challenge');
                                                                                                                            expect(notCrawlable).toBeTruthy();
                                                                                                                              });
                                                                                                                              
                                                                                                                                test('@SP-1940 @seo Start-Up AR page is NOT crawlable', async ({ page }) => {
                                                                                                                                    await formPage.gotoStartUpChallengeAr();
                                                                                                                                        const robotsContent = await formPage.getMetaRobotsContent();
                                                                                                                                            const robotsTxt = await formPage.checkRobotsTxt('https://gca.stg.alweb4tech.com');
                                                                                                                                                const notCrawlable = robotsContent.includes('noindex') || robotsTxt.includes('/Start-Up-Challenge');
                                                                                                                                                    expect(notCrawlable).toBeTruthy();
                                                                                                                                                      });
                                                                                                                                                      
                                                                                                                                                        test('@SP-1940 @smoke Start-Up EN is publicly accessible without login', async ({ browser }) => {
                                                                                                                                                            const context = await browser.newContext();
                                                                                                                                                                const page = await context.newPage();
                                                                                                                                                                    const fp = new ApplicationFormPage(page);
                                                                                                                                                                        await fp.gotoStartUpChallengeEn();
                                                                                                                                                                            expect(await fp.isPageLoaded()).toBeTruthy();
                                                                                                                                                                                await context.close();
                                                                                                                                                                                  });
                                                                                                                                                                                  
                                                                                                                                                                                    test('@SP-1940 @smoke Start-Up AR is publicly accessible without login', async ({ browser }) => {
                                                                                                                                                                                        const context = await browser.newContext();
                                                                                                                                                                                            const page = await context.newPage();
                                                                                                                                                                                                const fp = new ApplicationFormPage(page);
                                                                                                                                                                                                    await fp.gotoStartUpChallengeAr();
                                                                                                                                                                                                        expect(await fp.isPageLoaded()).toBeTruthy();
                                                                                                                                                                                                            await context.close();
                                                                                                                                                                                                              });
                                                                                                                                                                                                              
                                                                                                                                                                                                                test('@SP-1940 @regression @lang-en User submits Start-Up application in EN', async ({ page }) => {
                                                                                                                                                                                                                    await formPage.gotoStartUpChallengeEn();
                                                                                                                                                                                                                        if (await formPage.isFormVisible()) {
                                                                                                                                                                                                                              await formPage.fillApplicationForm({
                                                                                                                                                                                                                                      name: 'StartUp Applicant EN',
                                                                                                                                                                                                                                              email: 'startup.en@example.com',
                                                                                                                                                                                                                                                      phone: '+971500000005',
                                                                                                                                                                                                                                                              organization: 'Test StartUp EN',
                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                          await formPage.submitForm();
                                                                                                                                                                                                                                                                                expect(await formPage.successMessage.isVisible()).toBeTruthy();
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                        test('@SP-1940 @regression @lang-ar User submits Start-Up application in AR', async ({ page }) => {
                                                                                                                                                                                                                                                                                            await formPage.gotoStartUpChallengeAr();
                                                                                                                                                                                                                                                                                                if (await formPage.isFormVisible()) {
                                                                                                                                                                                                                                                                                                      await formPage.fillApplicationForm({
                                                                                                                                                                                                                                                                                                              name: 'مقدم طلب الشركة الناشئة',
                                                                                                                                                                                                                                                                                                                      email: 'startup.ar@example.com',
                                                                                                                                                                                                                                                                                                                              phone: '+971500000006',
                                                                                                                                                                                                                                                                                                                                      organization: 'شركة ناشئة اختبار',
                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                  await formPage.submitForm();
                                                                                                                                                                                                                                                                                                                                                        expect(await formPage.successMessage.isVisible()).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                test('@SP-1940 @negative @lang-en Empty form shows validation errors EN', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                    await formPage.gotoStartUpChallengeEn();
                                                                                                                                                                                                                                                                                                                                                                        if (await formPage.isFormVisible()) {
                                                                                                                                                                                                                                                                                                                                                                              await formPage.submitForm();
                                                                                                                                                                                                                                                                                                                                                                                    const errors = await formPage.getValidationErrors();
                                                                                                                                                                                                                                                                                                                                                                                          expect(errors.length).toBeGreaterThan(0);
                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                  test('@SP-1940 @negative @lang-ar Empty form shows validation errors AR', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                      await formPage.gotoStartUpChallengeAr();
                                                                                                                                                                                                                                                                                                                                                                                                          if (await formPage.isFormVisible()) {
                                                                                                                                                                                                                                                                                                                                                                                                                await formPage.submitForm();
                                                                                                                                                                                                                                                                                                                                                                                                                      const errors = await formPage.getValidationErrors();
                                                                                                                                                                                                                                                                                                                                                                                                                            expect(errors.length).toBeGreaterThan(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                  });
