import { test, expect } from '@playwright/test';
import { CoordinatorDashboardPage } from '../../pages/CoordinatorDashboardPage';
import { testData } from '../../fixtures/testData';

/**
 * SP-1952 - University Challenge Dashboard - Coordinator
  * SP-1953 - Start-Up Challenge Dashboard - Coordinator
   *
    * NOTE: Coordinator credentials are TBD (not yet developed).
     * These tests are structured with skip annotations and will be enabled
      * when coordinator accounts become available.
       * Use testData.uniCoordinatorEmail / testData.startupCoordinatorEmail when ready.
        */

        test.describe('SP-1952 | University Challenge Coordinator Dashboard @regression', () => {
          let dashPage: CoordinatorDashboardPage;

            // Skip until coordinator credentials are available
              test.skip(() => !testData.uniCoordinatorEmail, 'University coordinator not yet developed');

                test.beforeEach(async ({ page }) => {
                    dashPage = new CoordinatorDashboardPage(page);
                        await dashPage.loginAsCoordinator(
                              testData.adminUrl,
                                    testData.uniCoordinatorEmail,
                                          testData.uniCoordinatorPassword
                                              );
                                                });

                                                  test('@SP-1952 @smoke University Coordinator dashboard loads', async ({ page }) => {
                                                      await expect(page.locator('body')).toBeVisible();
                                                          const title = await dashPage.getDashboardTitle();
                                                              expect(title.length).toBeGreaterThan(0);
                                                                });

                                                                  test('@SP-1952 @smoke University Coordinator sees applications table', async ({ page }) => {
                                                                      await expect(dashPage.applicationsTable).toBeVisible();
                                                                        });

                                                                          test('@SP-1952 @smoke University Coordinator sees total applications count', async ({ page }) => {
                                                                              const total = await dashPage.getTotalApplicationsCount();
                                                                                  expect(total).toBeTruthy();
                                                                                    });

                                                                                      test('@SP-1952 @regression University Coordinator can filter applications by pending', async ({ page }) => {
                                                                                          await dashPage.filterByStatus('pending');
                                                                                              await expect(dashPage.applicationsTable).toBeVisible();
                                                                                                });

                                                                                                  test('@SP-1952 @regression University Coordinator can view application details', async ({ page }) => {
                                                                                                      const count = await dashPage.getApplicationCount();
                                                                                                          if (count > 0) {
                                                                                                                await dashPage.clickViewApplication(0);
                                                                                                                      await expect(page.locator('body')).toBeVisible();
                                                                                                                          }
                                                                                                                            });
                                                                                                                            
                                                                                                                              test('@SP-1952 @regression University Coordinator can approve application', async ({ page }) => {
                                                                                                                                  const count = await dashPage.getApplicationCount();
                                                                                                                                      if (count > 0) {
                                                                                                                                            await dashPage.clickViewApplication(0);
                                                                                                                                                  await dashPage.approveApplication();
                                                                                                                                                        expect(await dashPage.isSuccessAlertVisible()).toBeTruthy();
                                                                                                                                                            }
                                                                                                                                                              });
                                                                                                                                                              
                                                                                                                                                                test('@SP-1952 @regression University Coordinator can reject application', async ({ page }) => {
                                                                                                                                                                    const count = await dashPage.getApplicationCount();
                                                                                                                                                                        if (count > 0) {
                                                                                                                                                                              await dashPage.clickViewApplication(0);
                                                                                                                                                                                    await dashPage.rejectApplication();
                                                                                                                                                                                          expect(await dashPage.isSuccessAlertVisible()).toBeTruthy();
                                                                                                                                                                                              }
                                                                                                                                                                                                });
                                                                                                                                                                                                
                                                                                                                                                                                                  test('@SP-1952 @regression University Coordinator cannot see other challenge types', async ({ page }) => {
                                                                                                                                                                                                      const challengeType = await dashPage.getChallengeType();
                                                                                                                                                                                                          expect(challengeType.toLowerCase()).toMatch(/university|uni/i);
                                                                                                                                                                                                            });
                                                                                                                                                                                                            });
                                                                                                                                                                                                            
                                                                                                                                                                                                            test.describe('SP-1953 | Start-Up Challenge Coordinator Dashboard @regression', () => {
                                                                                                                                                                                                              let dashPage: CoordinatorDashboardPage;
                                                                                                                                                                                                              
                                                                                                                                                                                                                // Skip until coordinator credentials are available
                                                                                                                                                                                                                  test.skip(() => !testData.startupCoordinatorEmail, 'Start-Up coordinator not yet developed');
                                                                                                                                                                                                                  
                                                                                                                                                                                                                    test.beforeEach(async ({ page }) => {
                                                                                                                                                                                                                        dashPage = new CoordinatorDashboardPage(page);
                                                                                                                                                                                                                            await dashPage.loginAsCoordinator(
                                                                                                                                                                                                                                  testData.adminUrl,
                                                                                                                                                                                                                                        testData.startupCoordinatorEmail,
                                                                                                                                                                                                                                              testData.startupCoordinatorPassword
                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                      test('@SP-1953 @smoke Start-Up Coordinator dashboard loads', async ({ page }) => {
                                                                                                                                                                                                                                                          await expect(page.locator('body')).toBeVisible();
                                                                                                                                                                                                                                                              const title = await dashPage.getDashboardTitle();
                                                                                                                                                                                                                                                                  expect(title.length).toBeGreaterThan(0);
                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                      test('@SP-1953 @smoke Start-Up Coordinator sees applications table', async ({ page }) => {
                                                                                                                                                                                                                                                                          await expect(dashPage.applicationsTable).toBeVisible();
                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                              test('@SP-1953 @smoke Start-Up Coordinator sees total applications count', async ({ page }) => {
                                                                                                                                                                                                                                                                                  const total = await dashPage.getTotalApplicationsCount();
                                                                                                                                                                                                                                                                                      expect(total).toBeTruthy();
                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                          test('@SP-1953 @regression Start-Up Coordinator can filter applications by pending', async ({ page }) => {
                                                                                                                                                                                                                                                                                              await dashPage.filterByStatus('pending');
                                                                                                                                                                                                                                                                                                  await expect(dashPage.applicationsTable).toBeVisible();
                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                      test('@SP-1953 @regression Start-Up Coordinator can view application details', async ({ page }) => {
                                                                                                                                                                                                                                                                                                          const count = await dashPage.getApplicationCount();
                                                                                                                                                                                                                                                                                                              if (count > 0) {
                                                                                                                                                                                                                                                                                                                    await dashPage.clickViewApplication(0);
                                                                                                                                                                                                                                                                                                                          await expect(page.locator('body')).toBeVisible();
                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                  test('@SP-1953 @regression Start-Up Coordinator can approve application', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                      const count = await dashPage.getApplicationCount();
                                                                                                                                                                                                                                                                                                                                          if (count > 0) {
                                                                                                                                                                                                                                                                                                                                                await dashPage.clickViewApplication(0);
                                                                                                                                                                                                                                                                                                                                                      await dashPage.approveApplication();
                                                                                                                                                                                                                                                                                                                                                            expect(await dashPage.isSuccessAlertVisible()).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                    test('@SP-1953 @regression Start-Up Coordinator can reject application', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                        const count = await dashPage.getApplicationCount();
                                                                                                                                                                                                                                                                                                                                                                            if (count > 0) {
                                                                                                                                                                                                                                                                                                                                                                                  await dashPage.clickViewApplication(0);
                                                                                                                                                                                                                                                                                                                                                                                        await dashPage.rejectApplication();
                                                                                                                                                                                                                                                                                                                                                                                              expect(await dashPage.isSuccessAlertVisible()).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                      test('@SP-1953 @regression Start-Up Coordinator cannot see other challenge types', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                          const challengeType = await dashPage.getChallengeType();
                                                                                                                                                                                                                                                                                                                                                                                                              expect(challengeType.toLowerCase()).toMatch(/start.?up|startup/i);
                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                  test('@SP-1953 @negative Start-Up Coordinator cannot access University dashboard', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                      // Coordinator should only see their own challenge type
                                                                                                                                                                                                                                                                                                                                                                                                                          const challengeType = await dashPage.getChallengeType();
                                                                                                                                                                                                                                                                                                                                                                                                                              expect(challengeType.toLowerCase()).not.toMatch(/university|uni/i);
                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                });
